export const ROUTES = {
  HOME: "/",
  USER_PROFILE: "/user-profile",
  AUTH_CALLBACK: "/auth-callback",
  MANAGE_USER_RESTURANT: "/manage-resturant"
}
export const CUISINES_LIST = [
  "American",
  "BBQ",
  "Breakfast",
  "Burgers",
  "Cafe",
  "Chinese",
  "Desserts",
  "French",
  "Greek",
  "Healthy",
  "Indian",
  "Italian",
  "Japanese",
  "Mexican",
  "Noodles",
  "Organic",
  "Pasta",
  "Pizza",
  "Salads",
  "Seafood",
  "Spanish",
  "Steak",
  "Sushi",
  "Tacos",
  "Tapas",
  "Vegan",
];
